### ISSUE TITLE
bug triage: "get client" problem

### ISSUE THREAD

**Issue by Csedge** [Csedge/TeamSpeak-3-Java-API#1]
For the “get client” problem, we found a built-in function for client object called getId() which returns the actual uid of the client. We can just simply add an additional helper function called getClientIdByNameExact in TS3Api.java with simple codes below:

public int getClientIdByNameExact(String name, boolean ignoreCase){
		return getClientByNameExact(name,ignoreCase).getId();
	}

**Comment by nosnatef** [comment]
Get the issue addressed.
